### PR TITLE
Add a tip on enabling Subresource Integrity for assets served from CDN

### PR DESCRIPTION
**Pull request by JuanitoFatas**
👋 

With this enable, asset will Include checksum that browser will validate to see if asset is compromised. Avoid XSS attack.

A requirement for [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to work correctly is to [partner with CORS](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) (either set to `anonymous` or `use-credentials`.

Most modern browsers support this, and see also [how GitHub is using it](https://githubengineering.com/subresource-integrity/).

<kbd>[Preview Changed README](https://github.com/ankane/secure_rails/blob/b8b2b0b24c588b7800bafc23cdf8c029e82416b4/README.md)</kbd>

### CODE REVIEW

**Comment by ankane** [comment]
Hey @JuanitoFatas, thanks for the PR 👍 From my understanding, this should only be needed when loading assets from an CDN.

**Comment by ankane** [comment]
Hey @JuanitoFatas, thoughts on the comment above?

**Comment by JuanitoFatas** [comment]
Sorry for delayed response, yes this is good tip for assets behind CDN. Do you think this is out of scope for this project or we could better rephrase it? Thank you as always, Andrew.

**Comment by ankane** [comment]
I think it's in scope, but want to make it clear that it applies to CDNs. I added this tip since you posted it - "Don’t use assets from a public CDN, as this creates unnecessary availability and security risk" - but think it still applies to assets from your own CDN (which is likely run by a 3rd party).

**Comment by JuanitoFatas** [comment]
> I think it's in scope, but want to make it clear that it applies to CDNs. I added this tip since you posted it - "Don’t use assets from a public CDN, as this creates unnecessary availability and security risk" - but think it still applies to assets from your own CDN (which is likely run by a 3rd party).

Did not notice you added a new tip, awesome.

Updated this Pull request, thanks 🙇🙇🙇🙇🙇🙇🙇

**Pull request closed without merging**
